### ISSUE TITLE
Crash when loading the world

### ISSUE THREAD

**Issue by AltimusX** [Ladysnake/Creeper-Spores#10]
https://pastebin.com/19RavYGs

I've never been able to load this. 

This crash happens when I try to load my save game, or start a new one.   Also noteable is this crashes when I only use just the bare minimum of mods.

**Comment by endavis** [comment]
Here's mine:
https://paste.ee/p/93NiQ

**Comment by Pyrofab** [comment]
Thank you for the report, it should be fixed now.
