### ISSUE TITLE
zh_cn

### ISSUE THREAD

**Issue by yuwanjun564** [Ladysnake/Creeper-Spores#12]
{
  "effect.creeperspores.creeper_spore": "苦力怕孢子",
  "effect.creeperspores.generic_spore": "%s 孢子",
  "entity.creeperspores.creeperling": "小只苦力怕",
  "item.creeperspores.creeperling_spawn_egg": "小只苦力怕生成蛋"
}

**Comment by Pyrofab** [comment]
Thanks for your contribution ! Added in latest release.
