### ISSUE TITLE
Creeperlings don't have the Creeper post-processing shader when spectating as them

### ISSUE THREAD

**Issue by floral-qua-floral** [Ladysnake/Creeper-Spores#26]
Spectating as a Creeper:
![2022-02-01_12 40 25](https://user-images.githubusercontent.com/49110090/152021848-3dd93ce3-66b2-44fe-b88b-ebdf56a93ca4.png)
(An additional line is also added to the F3 debug screen reading: "Shader: minecraft:shaders/post/creeper.json")

Spectating as a Creeperling:
![2022-02-01_12 40 29](https://user-images.githubusercontent.com/49110090/152021858-4d2ab3b2-750d-470e-becd-ed1fa2064285.png)

yeah i'll be honest this is possibly the least important bug report i've ever submitted

**Comment by Pyrofab** [comment]
Fair 'nuff
