### ISSUE TITLE
Creeper Spores causes Client crashes

### ISSUE THREAD

**Issue by Ayutac** [Ladysnake/Creeper-Spores#31]
Bug report: https://paste.ee/p/lrlLI

Minecraft 1.18.2, Fabric 0.47.10, Creeper Spores 1.8.0

How to reproduce:
1. Start new world
2. Give yourself any effect, I did it via a fire resistence splash potion
3. Open inventory
4. Open green recipe book
5. Hover over effect
6. Client crashes.

Noticed it first with Creeper Spores effect while playing my custom mod pack, but I ran on Vanilla, Vanilla+Fabric, Vanilla+Fabric+API and Vanilla+Fabric+API+Creeper-Spores and only in the last one the crash happens.

I suppose this hasn't been noticed earlier because most mod players use REI instead of the recipe book.

**Comment by IcestarLoki** [comment]
Same crash on 1.18.1, only noticed on creeper spores effect but didn't try others

**Comment by Pyrofab** [comment]
Oops, apologies for not checking this sooner. A fix is on the way for 1.19.

**Comment by Eman-3600** [comment]
Oh so that's what was causing the crash on this one server I played on? Strange.

**Comment by Derpford** [comment]
Will this fix be backported to 1.18.2?

**Comment by LonelyMusicDisc** [comment]
I too would appreciate that.
