### ISSUE TITLE
Creeper Overhaul Compatibility

### ISSUE THREAD

**Issue by ardissaps** [Ladysnake/Creeper-Spores#33]
Is it compatible with [Creeper Overhaul Mods](https://www.curseforge.com/minecraft/mc-mods/creeper-overhaul)(not the resourcepack version)?

**Comment by Pyrofab** [comment]
Would you mind trying it and reporting back ? Creeperlings should use the creeper texture, but I do not know how they will react to alternative models.

**Comment by ardissaps** [comment]
Their creeper is different from each biome, not only the model but also change behaviour, I post wrong link, what I should link is not the resource pack version but mod version here : [Creeper Overhaul Mods](https://www.curseforge.com/minecraft/mc-mods/creeper-overhaul) (I will also edit earlier post)

**Comment by Pyrofab** [comment]
Closing this as duplicate of #28
