### ISSUE TITLE
Fabric No Longer Supported

### ISSUE THREAD

**Issue by Floofs-Dev** [Ladysnake/Creeper-Spores#34]
Releases for 1.19.x are no longer compatible with Fabric Loader, but the documentation (readme.md) still show 'A Minecraft mod for the Fabric Mod Loader'

**Comment by Floofs-Dev** [comment]
The Changelog.md also makes no mention of the Fabric->Quilt switch for Creeper-Spores 1.9.0 and newer

**Comment by Ayutac** [comment]
Oh that's why they suddenly explode.

Do you need help with the update or can you give up the maintainence to someone else?

**Comment by Ayutac** [comment]
I'll take that as a No and upload the fabric version to CF myself

**Comment by Pyrofab** [comment]
Oh, I thought the question was "Do you need help updating the readme and description?", which sounded a bit overkill.
I'd rather you asked for permission before porting the mod back to Fabric, and in fact I'd rather you don't do such a port at all. That said, I can't actually stop you as long as you abide by the license - though I'd at least ask for some control over any curseforge project that arises from this.

**Comment by Ayutac** [comment]
Sorry for the confusion. I take this maintenance task on myself because I played with the mod and want to continue to do so. That I respect the licence was a given from my POV.

I wonder why you want to _actively_ discontinue fabric development? I get "I don't want to develop this for fabric anymore since I don't use it myself", I don't get "No one should be allowed to use this on fabric anymore."

Would you prefer maintaining a fabric version via me on your github and curseforge or me opening up an extra curseforge project?

**Comment by Pyrofab** [comment]
In case you are not aware, Quilt is designed to work with existing Fabric mods, so users should not have to sacrifice their existing modpack to keep playing with the latest versions of Creeper Spores - although there are some exceptions documented [on the quilt forum](https://forum.quiltmc.org/t/mod-incompatibility-megathread/261).
My goals when switching the mod to be quilt-only were to myself benefit from future quilt-specific improvements, but also to promote the loader and its use. Maintaining a Fabric version myself would work against both those goals, and simply having a competing Fabric version would infringe on the latter.

**Comment by Ayutac** [comment]
Tbh this sounds like gatekeeping. But you do you. Good luck!

**Comment by Pyrofab** [comment]
I don't think we use the same definition of gatekeeping but alright. Thanks for respecting our wishes.

**Comment by Pyrofab** [comment]
@Ayutac Hey, saw you ended up publishing on Curseforge regardless. Could you maybe at least add me as Former Author on the project page ?

**Comment by Ayutac** [comment]
I did me. Added you.
