### ISSUE TITLE
Suggestion: add NBT tag to determine if a creeper will let of spores

### ISSUE THREAD

**Issue by Nathan22211** [Ladysnake/Creeper-Spores#4]
this NBT (I'd probably use {giveSpores:(0 or 1)b} will be set to 0 on entities that extend the creeper AI that have their AI turned of via NBT (yes no AI creepers still give creeper spores)

**Comment by Pyrofab** [comment]
So this is basically a suggestion for modpack makers and command users right ? The goal would be to control spore release for individual creepers ?

**Comment by Nathan22211** [comment]
pretty much, otherwise datapack made explosives that use creepers would be spawning creeperlings
